language: go

matrix:
  include:
    - go: 1.7
    - go: 1.8
    - go: tip
  allow_failures:
    - go: tip

go_import_path: github.com/oracle/terraform-provider-baremetal

script:
  - go test -v -race $(go list ./... | grep -v '/vendor/')
